
import "./App.css";

const countries = [
  {
    name: "United States of America",
    shortName: "USA",
    details: "The United States is a federal republic in North America with 50 states.",
    image: "https://example.com/usa-image.jpg",
    mapLink: "https://goo.gl/maps/usa",
    phoneCode: "+1",
    countryCode: "US",
    topCities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    gdp: "23.32 trillion USD (2023 estimate)",
    mainLanguage: "English",
    otherLanguages: ["Spanish", "Chinese", "French"],
    currency: "US Dollar",
    currencyPrice: "1 USD = 0.93 EUR",
    currentTime: new Date().toLocaleString("en-US", { timeZone: "America/New_York" }),
    region: "North America",
  },
  {
    name: "India",
    shortName: "IND",
    details: "India is a South Asian country known for its rich culture and diverse population.",
    image: "https://example.com/india-image.jpg",
    mapLink: "https://goo.gl/maps/india",
    phoneCode: "+91",
    countryCode: "IN",
    topCities: ["Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai"],
    gdp: "3.73 trillion USD (2023 estimate)",
    mainLanguage: "Hindi",
    otherLanguages: ["English", "Bengali", "Telugu"],
    currency: "Indian Rupee",
    currencyPrice: "1 USD = 83.20 INR",
    currentTime: new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }),
    region: "Asia",
  },
  {
    name: "China",
    shortName: "CHN",
    details: "China, officially the People's Republic of China, is the world's most populous country.",
    image: "https://example.com/china-image.jpg",
    mapLink: "https://goo.gl/maps/china",
    phoneCode: "+86",
    countryCode: "CN",
    topCities: ["Beijing", "Shanghai", "Shenzhen", "Guangzhou", "Chengdu"],
    gdp: "19.37 trillion USD (2023 estimate)",
    mainLanguage: "Mandarin",
    otherLanguages: ["Cantonese", "Shanghainese"],
    currency: "Renminbi (Yuan)",
    currencyPrice: "1 USD = 7.27 CNY",
    currentTime: new Date().toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" }),
    region: "Asia",
  },
  {
    name: "Germany",
    shortName: "GER",
    details: "Germany is a European country known for its advanced economy and rich history.",
    image: "https://example.com/germany-image.jpg",
    mapLink: "https://goo.gl/maps/germany",
    phoneCode: "+49",
    countryCode: "DE",
    topCities: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne"],
    gdp: "4.55 trillion USD (2023 estimate)",
    mainLanguage: "German",
    otherLanguages: ["English", "Turkish"],
    currency: "Euro",
    currencyPrice: "1 EUR = 1.07 USD",
    currentTime: new Date().toLocaleString("de-DE", { timeZone: "Europe/Berlin" }),
    region: "Europe",
  },
  {
    name: "United Kingdom",
    shortName: "UK",
    details: "The United Kingdom consists of four countries: England, Scotland, Wales, and Northern Ireland.",
    image: "https://example.com/uk-image.jpg",
    mapLink: "https://goo.gl/maps/uk",
    phoneCode: "+44",
    countryCode: "GB",
    topCities: ["London", "Manchester", "Birmingham", "Glasgow", "Liverpool"],
    gdp: "3.66 trillion USD (2023 estimate)",
    mainLanguage: "English",
    otherLanguages: ["Welsh", "Scottish Gaelic"],
    currency: "Pound Sterling",
    currencyPrice: "1 GBP = 1.22 USD",
    currentTime: new Date().toLocaleString("en-GB", { timeZone: "Europe/London" }),
    region: "Europe",
  },
  {
    name: "Brazil",
    shortName: "BRA",
    details: "Brazil is the largest country in South America, known for the Amazon rainforest and vibrant culture.",
    image: "https://example.com/brazil-image.jpg",
    mapLink: "https://goo.gl/maps/brazil",
    phoneCode: "+55",
    countryCode: "BR",
    topCities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"],
    gdp: "2.06 trillion USD (2023 estimate)",
    mainLanguage: "Portuguese",
    otherLanguages: ["Spanish", "German", "Italian"],
    currency: "Brazilian Real",
    currencyPrice: "1 USD = 5.31 BRL",
    currentTime: new Date().toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" }),
    region: "South America",
  },
  {
    name: "Japan",
    shortName: "JPN",
    details: "Japan is an East Asian country known for its rich cultural heritage and advanced technology.",
    image: "https://example.com/japan-image.jpg",
    mapLink: "https://goo.gl/maps/japan",
    phoneCode: "+81",
    countryCode: "JP",
    topCities: ["Tokyo", "Osaka", "Nagoya", "Yokohama", "Fukuoka"],
    gdp: "4.23 trillion USD (2023 estimate)",
    mainLanguage: "Japanese",
    otherLanguages: ["English", "Korean"],
    currency: "Japanese Yen",
    currencyPrice: "1 USD = 149.26 JPY",
    currentTime: new Date().toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" }),
    region: "Asia",
  },
  {
    name: "Australia",
    shortName: "AUS",
    details: "Australia is a country and continent known for its natural wonders and diverse wildlife.",
    image: "https://example.com/australia-image.jpg",
    mapLink: "https://goo.gl/maps/australia",
    phoneCode: "+61",
    countryCode: "AU",
    topCities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    gdp: "1.70 trillion USD (2023 estimate)",
    mainLanguage: "English",
    otherLanguages: ["Mandarin", "Arabic"],
    currency: "Australian Dollar",
    currencyPrice: "1 USD = 1.57 AUD",
    currentTime: new Date().toLocaleString("en-AU", { timeZone: "Australia/Sydney" }),
    region: "Oceania",
  },
  {
    name: "France",
    shortName: "FRA",
    details: "France is a Western European country known for its culture, art, and historical landmarks.",
    image: "https://example.com/france-image.jpg",
    mapLink: "https://goo.gl/maps/france",
    phoneCode: "+33",
    countryCode: "FR",
    topCities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
    gdp: "3.34 trillion USD (2023 estimate)",
    mainLanguage: "French",
    otherLanguages: ["Arabic", "Portuguese"],
    currency: "Euro",
    currencyPrice: "1 EUR = 1.07 USD",
    currentTime: new Date().toLocaleString("fr-FR", { timeZone: "Europe/Paris" }),
    region: "Europe",
  },
  {
    name: "Canada",
    shortName: "CAN",
    details: "Canada is a country in North America known for its vast natural landscapes and multicultural cities.",
    image: "https://example.com/canada-image.jpg",
    mapLink: "https://goo.gl/maps/canada",
    phoneCode: "+1",
    countryCode: "CA",
    topCities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
    gdp: "2.14 trillion USD (2023 estimate)",
    mainLanguage: "English",
    otherLanguages: ["French"],
    currency: "Canadian Dollar",
    currencyPrice: "1 USD = 1.36 CAD",
    currentTime: new Date().toLocaleString("en-CA", { timeZone: "America/Toronto" }),
    region: "North America",
  }
  // Add 10 more countries following the same structure.
];

function App() {
 
  return (
    <div>
    
    </div>
  );
}

export default App;
